source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TASettings_Example', :exclusive => true do
  pod "TASettings", :path => "../"
end

target 'TASettings_Tests', :exclusive => true do
  pod "TASettings", :path => "../"

  
end
